style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/KeisukeYamashita/terraform-aws-vpc-peeering-mongo-atlas
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
      -
